kafka:
  producer:
    brokers: ${KAFKA_BROKERS}
    acks: all
    retries: 5
    request-timeout-ms: 60000
  consumer:
    group-id: ${KAFKA_CONSUMER_GROUP:kraken-cis-group}
  topic:
    alarms: ${KAFKA_TOPIC_ALARMS:kraken-alarm-events}
